config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/:id', to: 'users#show', as: 'user'
  get '/', to: 'application#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout',to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  
  # campsite routes
  resources :campsites, only: [:index, :show, :new, :create, :edit, :update] do
    resources :comments
  end
  
  get '/favorites', to: 'favorites#index'
  post '/favorites', to: 'favorites#create'
  get '/best_campsite', to: 'favorites#most_favorite'
  get '/favorites_with_notes', to: 'favorites#fav_with_notes'
  get '/search', to: 'campsites#search'
  get '/list', to: 'comments#list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campsite.rb
class Campsite < ApplicationRecord
  validates :name, :uniqueness => true
  validates :name, :presence => true
  has_many :favorites
  has_many :users, through: :favorites
  has_many :comments
  
  def self.find_by_location(location)
     where("address LIKE ?", location).order(:name)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :title, :uniqueness => true
  belongs_to :campsite
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validate :no_repeat_favorites
  belongs_to :user
  belongs_to :campsite
  scope :with_notes, -> { where(note: true) }
  
  def no_repeat_favorites
    existing_favorites = Favorite.where(campsite_id: campsite_id, user_id: user_id) 
  
    if existing_favorites.exists? 
      errors.add :favorite, 'already added to Favorites'
    end
  end
  
  def self.most_favorite
    best_id = Favorite.all.group(:campsite_id).count.max_by{|k,v| v}[0]
    Campsite.find(best_id)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :name, :message => "has been taken"
  validates_presence_of :name, :message => "can't be blank"
  validates :password, :confirmation => true
  validates :password_confirmation, :presence => true
  
  has_many :favorites
  has_many :campsites, through: :favorites
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login, except: [:home]
  helper_method :current_user
  helper_method :logged_in?
  protect_from_forgery
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
  def home
    render :layout => "no_nav"
  end
  
  private
 
  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to "/"
    end
  end
end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController
  
  def index
    @campsites = Campsite.all
    render json: @campsites
  end
  
  def new
    @campsite = Campsite.new
  end
  
  def create
    @campsite = Campsite.find_by(name: params[:campsite][:name])
    if @campsite
      # flash[:message] = ""
      # redirect_to new_campsite_path
      render json: {message: 'A campsite with that name already exists!'}
    else
      @campsite = Campsite.create(campsite_args)
        render json: @campsite
      # respond_to do |f|
        # f.html {redirect_to campsite_path(@campsite)}
      # end
    end
  end
  
  def show
    @campsite = Campsite.find_by(id: params[:id])
    @comment = @campsite.comments.build
    render json: @campsite
  end
  
  def edit
    @campsite = Campsite.find_by(id: params[:id])
  end
  
  def update
    @campsite = Campsite.find_by(id: params[:id])
    @campsite.update(address: params[:campsite][:address], description: params[:campsite][:description])
    redirect_to campsite_path(@campsite)
  end

  def search
     @list = Campsite.find_by_location(params[:location])
  end
  
  
 private
  def campsite_args
    params.require(:campsite).permit(:name, :address, :description)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @campsite = Campsite.find_by(id: params[:campsite_id])
    @comment = @campsite.comments.build
  end
  
  def create
    @campsite = Campsite.find_by(id: params[:campsite_id])
    @comment = @campsite.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to campsite_comments_path(@campsite)
  end
  
  def index
    @campsite = Campsite.find_by(id: params[:campsite_id])
    @comments = @campsite.comments
  end
  
  def list
    @user = current_user
    @comments = @user.comments
  end
  
 private
  def comment_params
    params.require(:comment).permit(:title, :text)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
 def index
   @favorites = current_user.favorites
  #  render 'index'
  render json: @favorites
 end
 
 def create
   @campsite = Campsite.find_by(id: params[:campsite_id])
   @favorite = Favorite.new
   @favorite.campsite_id = @campsite.id
   @favorite.user_id = current_user.id
   @favorite.note = params[:note]
   if @favorite.save
    render json: @favorite
   else
    # flash[:message] = @favorite.errors.messages[:favorite].first
    # redirect_to campsites_path
    render json: {message: 'Unable to add to favorites!'}
   end
 end
 
 def most_favorite
   @best = Favorite.most_favorite
 end
 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  
  def new
    @user= User.new
    render :layout => "no_nav"
  end


  def create
    if auth_hash = request.env['omniauth.auth']
      
#       Existing user
      if @user = User.find_by(uid: auth_hash['uid'])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
#         New user
        @user = User.new(uid: auth_hash['uid'], name: auth_hash['info']['first_name'], password: SecureRandom.hex)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        end
      end
    else
      @user = User.find_by(name: params[:user][:name])
        if @user && @user.authenticate(params[:user][:password])
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          flash[:message] = "Wrong credentials"
          redirect_to '/'
        end
    end
  end
  
  def destroy
    session.delete :user_id
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  skip_before_action :verify_authenticity_token, only: [:create]

   
  def new
    @user = User.new
    render :layout => "no_nav"
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:message] = "User could not be created"
      redirect_to '/'
    end
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def index
    @user = User.find_by(id: params[:id])
    @comments = @user.comments
  end
  
private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<div class='block'>
    <h1 class="title"> Welcome to RVroutes!</h1>

    <h4 class="title is-4"><%= link_to "Sing up", signup_path %></h4>
    <h4 class="title is-4"><%= link_to "Log in", login_path %></h4>
    <h4 class="title is-4"><%= link_to "Log in via GOOGLE", '/auth/google_oauth2' %></h4>
</div>

app/views/campsites/_form.html.erb
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
	<%= f.label :address %>
	<%= f.text_field :address %>
	</p>
	<p>
	<%= f.label :description %>
	<%= f.text_field :description %>
	</p>
	<%= f.submit %>

app/views/campsites/edit.html.erb
<h1>Create a new campsite here</h1>
<%= form_for @campsite do |f|%>
	<%= render 'form', f: f %>
<% end%>

app/views/campsites/index.html.erb
<% @campsites.each do |campsite| %>
<p>
	<h3><%= link_to campsite.name, campsite_path(campsite) %></h3>
	<%= campsite.address %></br>
	<%= campsite.description %></br>
	
	<% if !current_user.favorites.exists?(campsite_id: campsite.id) %>
		<%= form_tag("/favorites", method: "post") do %>
		  <%= hidden_field_tag(:campsite_id, campsite.id) %>
		  <%= label_tag(:note, "Add a note to your favorite") %>
		  <%= text_field_tag(:note) %>
		  <%= submit_tag("Add to favorites") %>
		<% end %>
	<% end %>
</p>
<% end %>

app/views/campsites/new.html.erb
<h1>Create a new campsite here</h1>
<%= form_for @campsite do |f|%>
	<%= render 'form', f: f %>
<% end%>

app/views/campsites/search.html.erb
<h3> Search by location:</h3>
<%= form_tag("/search", method: "get") do %>
	<%= text_field_tag(:location)%>
	<%= submit_tag ("Search") %>
<% end %>

</br>

<% @list.map do |camp| %>
<ul>
	<li>
		<%=  camp.name %>
		in
		<%= camp.address %>
	</li>
</ul>
<% end %>

app/views/campsites/show.html.erb
<h1><%= @campsite.name %></h1>

<h3>Address: <%= @campsite.address %></h3>
<h3>Description:</h3>
<p><%= @campsite.description %></p>

	
<%= link_to "See comments", campsite_comments_path(@campsite) %></br>
<%= link_to "Edit campsite", edit_campsite_path(@campsite) %>

app/views/comments/index.html.erb
<h2>Comments:</h2>
	<% @campsite.comments.each do |comment| %>
	<p>
		<h3><%= comment.title %></h3>
		<%= comment.text %></br>
		--------------------------------
	</p>
	<% end %>

<%= link_to "Add a comment", new_campsite_comment_path(@campsite) %>

app/views/comments/list.html.erb
<h3> <%= @user.name %> said  </h3>
<% @comments.each do |comment| %>
	<p>
		<%= comment.text %> about <strong><%= comment.campsite.name %></strong> 
	</p>
<% end %>

app/views/comments/new.html.erb
<h1>Add a comment here</h1>
<%= form_for ([@campsite, @comment]) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :text %>
	<%= f.text_field :text %>
	<%= f.submit %>
<% end %>

app/views/favorites/index.html.erb
<h1>Your favorite campsites are:</h1>
<% @favorites.each do |fav| %>
<p>
	<h3><%= fav.campsite.name %></h3>
	<%= fav.campsite.address %></br>
	<%= fav.campsite.description %></br>
	<%= fav.note %>
</p>
<% end %>

app/views/favorites/most_favorite.html.erb
<h3>The campsite most users liked is: </h3>
<%= link_to @best.name, campsite_path(@best) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RVroute</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  
    <link rel="stylesheet" href = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body style="max-width: 600px; text-align: center;">
   <div style="display: inline-block">
      <div class="block">
        <!--
          <a href="/campsites">All campsites</a>
          <a href="/campsites/new">Add campsite	</a>
          <a href="/favorites">Your personal favorites</a>
          <a href="/users/<%= current_user.id%>">Your profile</a>
          <a href="/best_campsite">Best campsite</a>
          <a href="/search">Search by location</a>
          <a href="/list">List all my comments</a>
          -->
          <div class="nav">
            <button id='camps' class='button is-primary'>All camps</button>
            <button id='new_camp' class='button is-primary nav-item'>New camp</button>
            <button id='favorites' class='button is-primary nav-item'>My favorites</button>
          </div>
      </div>
      
      <div class="container notification">
        <% flash.each do |key, message| %>
          <div class="alert alert-<%= key %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>

      <div id="fetch-data">
      </div>
    </div>
   </body>
</html>

app/views/layouts/no_nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RVroute</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body style="max-width: 600px; text-align: center;">
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
   </body>
</html>

app/views/users/new.html.erb
<%= form_for @user, url: 'signup' do |f| %>
    <div class='block'>
        <p>Name: <%= f.text_field :name %></p>
        <p>Password: <%= f.password_field :password %></p>
        <p>Password confirmation: <%= f.password_field :password_confirmation %></p>
        <%= f.submit "Submit" %>
        <% end %>
    </div>

app/views/users/show.html.erb
<% if logged_in? %>
	<h3 class='title is-3'> Hi, <%= current_user.name %>!</h3>

	<%= link_to "Log out", logout_path %>
<% else %>
	<% controller.redirect_to '/'%>
<% end %>